image:
  - Visual Studio 2022

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - '*.ps1'

environment:
  PCRE2_VERSION: 10.37
  EDITORCONFIG_VERSION: 0.12.5
  CONFIG: Release
  VSVER: 17
  matrix:
  - ARCH: x64
  - ARCH: x86
  - ARCH: arm64

install:
  - cmake --version
  - git submodule update --init
  # Download PCRE2 and editorconfig-core-c sources
  - ps: ./init.ps1 -pcre $env:PCRE2_VERSION -edc $env:EDITORCONFIG_VERSION
  # Build and install PCRE2
  - ps: ./build.ps1 -proj pcre2 -config $env:CONFIG -arch $env:ARCH -vsver $env:VSVER -init -install
  # Build and install editorconfig-core-c
  - ps: ./build.ps1 -proj core -config $env:CONFIG -arch $env:ARCH -vsver $env:VSVER -init -install

build_script:
  # Build and install editorconfig plugin
  - ps: ./build.ps1 -proj npp -config $env:CONFIG -arch $env:ARCH -vsver $env:VSVER -init -install

after_build:
  - ps: >-
        Push-AppveyorArtifact "bin\$env:ARCH\NppEditorConfig.dll" -FileName NppEditorConfig.dll

        if ($($env:APPVEYOR_REPO_TAG) -eq "true") {
            $ZipFileName = "NppEditorConfig_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:ARCH).zip"
            7z a $ZipFileName bin\$env:ARCH\NppEditorConfig.dll
        }

artifacts:
  - path: NppEditorConfig_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
